platform :ios, '11.0'


target 'Ve-scoverer' do


  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ve-scoverer

pod 'Firebase/Auth'
pod 'FirebaseFirestoreSwift'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
pod 'Firebase/Storage'
pod 'GoogleSignIn'
pod 'SDWebImage', '~> 5.0'
pod 'SwiftyToolTip'
pod 'Alamofire', '~> 5.2'



end
